/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PressRouteImport } from './routes/press'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalPartnerAgreementRouteImport } from './routes/legal.partner-agreement'
import { Route as LegalDataPracticesRouteImport } from './routes/legal.data-practices'
import { Route as LegalCreditDisclosureRouteImport } from './routes/legal.credit-disclosure'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPartnerAgreementRoute = LegalPartnerAgreementRouteImport.update({
  id: '/partner-agreement',
  path: '/partner-agreement',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDataPracticesRoute = LegalDataPracticesRouteImport.update({
  id: '/data-practices',
  path: '/data-practices',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreditDisclosureRoute = LegalCreditDisclosureRouteImport.update({
  id: '/credit-disclosure',
  path: '/credit-disclosure',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/credit-disclosure': typeof LegalCreditDisclosureRoute
  '/legal/data-practices': typeof LegalDataPracticesRoute
  '/legal/partner-agreement': typeof LegalPartnerAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/credit-disclosure': typeof LegalCreditDisclosureRoute
  '/legal/data-practices': typeof LegalDataPracticesRoute
  '/legal/partner-agreement': typeof LegalPartnerAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/credit-disclosure': typeof LegalCreditDisclosureRoute
  '/legal/data-practices': typeof LegalDataPracticesRoute
  '/legal/partner-agreement': typeof LegalPartnerAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/legal'
    | '/marketplace'
    | '/partners'
    | '/press'
    | '/sign-in'
    | '/sign-up'
    | '/admin/analytics'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/system'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/credit-disclosure'
    | '/legal/data-practices'
    | '/legal/partner-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/legal'
    | '/marketplace'
    | '/partners'
    | '/press'
    | '/sign-in'
    | '/sign-up'
    | '/admin/analytics'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/system'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/credit-disclosure'
    | '/legal/data-practices'
    | '/legal/partner-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/legal'
    | '/marketplace'
    | '/partners'
    | '/press'
    | '/sign-in'
    | '/sign-up'
    | '/admin/analytics'
    | '/admin/leads'
    | '/admin/products'
    | '/admin/system'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/credit-disclosure'
    | '/legal/data-practices'
    | '/legal/partner-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PressRoute: typeof PressRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/partner-agreement': {
      id: '/legal/partner-agreement'
      path: '/partner-agreement'
      fullPath: '/legal/partner-agreement'
      preLoaderRoute: typeof LegalPartnerAgreementRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/data-practices': {
      id: '/legal/data-practices'
      path: '/data-practices'
      fullPath: '/legal/data-practices'
      preLoaderRoute: typeof LegalDataPracticesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/credit-disclosure': {
      id: '/legal/credit-disclosure'
      path: '/credit-disclosure'
      fullPath: '/legal/credit-disclosure'
      preLoaderRoute: typeof LegalCreditDisclosureRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalCreditDisclosureRoute: typeof LegalCreditDisclosureRoute
  LegalDataPracticesRoute: typeof LegalDataPracticesRoute
  LegalPartnerAgreementRoute: typeof LegalPartnerAgreementRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalCreditDisclosureRoute: LegalCreditDisclosureRoute,
  LegalDataPracticesRoute: LegalDataPracticesRoute,
  LegalPartnerAgreementRoute: LegalPartnerAgreementRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PressRoute: PressRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
